/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoreIndexImport } from './routes/store/index'
import { Route as RoofingMagazineIndexImport } from './routes/roofing-magazine/index'
import { Route as PdfExtractorIndexImport } from './routes/pdf-extractor/index'
import { Route as MoneyModesIndexImport } from './routes/money-modes/index'
import { Route as LifeNotesIndexImport } from './routes/life-notes/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as GeminiChatIndexImport } from './routes/gemini-chat/index'
import { Route as ClassNotesIndexImport } from './routes/class-notes/index'
import { Route as BalanceChartIndexImport } from './routes/balance-chart/index'

// Create/Update Routes

const StoreIndexRoute = StoreIndexImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRoute,
} as any)

const RoofingMagazineIndexRoute = RoofingMagazineIndexImport.update({
  id: '/roofing-magazine/',
  path: '/roofing-magazine/',
  getParentRoute: () => rootRoute,
} as any)

const PdfExtractorIndexRoute = PdfExtractorIndexImport.update({
  id: '/pdf-extractor/',
  path: '/pdf-extractor/',
  getParentRoute: () => rootRoute,
} as any)

const MoneyModesIndexRoute = MoneyModesIndexImport.update({
  id: '/money-modes/',
  path: '/money-modes/',
  getParentRoute: () => rootRoute,
} as any)

const LifeNotesIndexRoute = LifeNotesIndexImport.update({
  id: '/life-notes/',
  path: '/life-notes/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const GeminiChatIndexRoute = GeminiChatIndexImport.update({
  id: '/gemini-chat/',
  path: '/gemini-chat/',
  getParentRoute: () => rootRoute,
} as any)

const ClassNotesIndexRoute = ClassNotesIndexImport.update({
  id: '/class-notes/',
  path: '/class-notes/',
  getParentRoute: () => rootRoute,
} as any)

const BalanceChartIndexRoute = BalanceChartIndexImport.update({
  id: '/balance-chart/',
  path: '/balance-chart/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/balance-chart/': {
      id: '/balance-chart/'
      path: '/balance-chart'
      fullPath: '/balance-chart'
      preLoaderRoute: typeof BalanceChartIndexImport
      parentRoute: typeof rootRoute
    }
    '/class-notes/': {
      id: '/class-notes/'
      path: '/class-notes'
      fullPath: '/class-notes'
      preLoaderRoute: typeof ClassNotesIndexImport
      parentRoute: typeof rootRoute
    }
    '/gemini-chat/': {
      id: '/gemini-chat/'
      path: '/gemini-chat'
      fullPath: '/gemini-chat'
      preLoaderRoute: typeof GeminiChatIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/life-notes/': {
      id: '/life-notes/'
      path: '/life-notes'
      fullPath: '/life-notes'
      preLoaderRoute: typeof LifeNotesIndexImport
      parentRoute: typeof rootRoute
    }
    '/money-modes/': {
      id: '/money-modes/'
      path: '/money-modes'
      fullPath: '/money-modes'
      preLoaderRoute: typeof MoneyModesIndexImport
      parentRoute: typeof rootRoute
    }
    '/pdf-extractor/': {
      id: '/pdf-extractor/'
      path: '/pdf-extractor'
      fullPath: '/pdf-extractor'
      preLoaderRoute: typeof PdfExtractorIndexImport
      parentRoute: typeof rootRoute
    }
    '/roofing-magazine/': {
      id: '/roofing-magazine/'
      path: '/roofing-magazine'
      fullPath: '/roofing-magazine'
      preLoaderRoute: typeof RoofingMagazineIndexImport
      parentRoute: typeof rootRoute
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/balance-chart': typeof BalanceChartIndexRoute
  '/class-notes': typeof ClassNotesIndexRoute
  '/gemini-chat': typeof GeminiChatIndexRoute
  '/home': typeof HomeIndexRoute
  '/life-notes': typeof LifeNotesIndexRoute
  '/money-modes': typeof MoneyModesIndexRoute
  '/pdf-extractor': typeof PdfExtractorIndexRoute
  '/roofing-magazine': typeof RoofingMagazineIndexRoute
  '/store': typeof StoreIndexRoute
}

export interface FileRoutesByTo {
  '/balance-chart': typeof BalanceChartIndexRoute
  '/class-notes': typeof ClassNotesIndexRoute
  '/gemini-chat': typeof GeminiChatIndexRoute
  '/home': typeof HomeIndexRoute
  '/life-notes': typeof LifeNotesIndexRoute
  '/money-modes': typeof MoneyModesIndexRoute
  '/pdf-extractor': typeof PdfExtractorIndexRoute
  '/roofing-magazine': typeof RoofingMagazineIndexRoute
  '/store': typeof StoreIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/balance-chart/': typeof BalanceChartIndexRoute
  '/class-notes/': typeof ClassNotesIndexRoute
  '/gemini-chat/': typeof GeminiChatIndexRoute
  '/home/': typeof HomeIndexRoute
  '/life-notes/': typeof LifeNotesIndexRoute
  '/money-modes/': typeof MoneyModesIndexRoute
  '/pdf-extractor/': typeof PdfExtractorIndexRoute
  '/roofing-magazine/': typeof RoofingMagazineIndexRoute
  '/store/': typeof StoreIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/balance-chart'
    | '/class-notes'
    | '/gemini-chat'
    | '/home'
    | '/life-notes'
    | '/money-modes'
    | '/pdf-extractor'
    | '/roofing-magazine'
    | '/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/balance-chart'
    | '/class-notes'
    | '/gemini-chat'
    | '/home'
    | '/life-notes'
    | '/money-modes'
    | '/pdf-extractor'
    | '/roofing-magazine'
    | '/store'
  id:
    | '__root__'
    | '/balance-chart/'
    | '/class-notes/'
    | '/gemini-chat/'
    | '/home/'
    | '/life-notes/'
    | '/money-modes/'
    | '/pdf-extractor/'
    | '/roofing-magazine/'
    | '/store/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BalanceChartIndexRoute: typeof BalanceChartIndexRoute
  ClassNotesIndexRoute: typeof ClassNotesIndexRoute
  GeminiChatIndexRoute: typeof GeminiChatIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LifeNotesIndexRoute: typeof LifeNotesIndexRoute
  MoneyModesIndexRoute: typeof MoneyModesIndexRoute
  PdfExtractorIndexRoute: typeof PdfExtractorIndexRoute
  RoofingMagazineIndexRoute: typeof RoofingMagazineIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  BalanceChartIndexRoute: BalanceChartIndexRoute,
  ClassNotesIndexRoute: ClassNotesIndexRoute,
  GeminiChatIndexRoute: GeminiChatIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LifeNotesIndexRoute: LifeNotesIndexRoute,
  MoneyModesIndexRoute: MoneyModesIndexRoute,
  PdfExtractorIndexRoute: PdfExtractorIndexRoute,
  RoofingMagazineIndexRoute: RoofingMagazineIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/balance-chart/",
        "/class-notes/",
        "/gemini-chat/",
        "/home/",
        "/life-notes/",
        "/money-modes/",
        "/pdf-extractor/",
        "/roofing-magazine/",
        "/store/"
      ]
    },
    "/balance-chart/": {
      "filePath": "balance-chart/index.tsx"
    },
    "/class-notes/": {
      "filePath": "class-notes/index.tsx"
    },
    "/gemini-chat/": {
      "filePath": "gemini-chat/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/life-notes/": {
      "filePath": "life-notes/index.tsx"
    },
    "/money-modes/": {
      "filePath": "money-modes/index.tsx"
    },
    "/pdf-extractor/": {
      "filePath": "pdf-extractor/index.tsx"
    },
    "/roofing-magazine/": {
      "filePath": "roofing-magazine/index.tsx"
    },
    "/store/": {
      "filePath": "store/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
