/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoreIndexImport } from './routes/store/index'
import { Route as RoofingMagazineIndexImport } from './routes/roofing-magazine/index'
import { Route as MoneyModesIndexImport } from './routes/money-modes/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as BrontosaurusIndexImport } from './routes/brontosaurus/index'

// Create/Update Routes

const StoreIndexRoute = StoreIndexImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRoute,
} as any)

const RoofingMagazineIndexRoute = RoofingMagazineIndexImport.update({
  id: '/roofing-magazine/',
  path: '/roofing-magazine/',
  getParentRoute: () => rootRoute,
} as any)

const MoneyModesIndexRoute = MoneyModesIndexImport.update({
  id: '/money-modes/',
  path: '/money-modes/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const BrontosaurusIndexRoute = BrontosaurusIndexImport.update({
  id: '/brontosaurus/',
  path: '/brontosaurus/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/brontosaurus/': {
      id: '/brontosaurus/'
      path: '/brontosaurus'
      fullPath: '/brontosaurus'
      preLoaderRoute: typeof BrontosaurusIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/money-modes/': {
      id: '/money-modes/'
      path: '/money-modes'
      fullPath: '/money-modes'
      preLoaderRoute: typeof MoneyModesIndexImport
      parentRoute: typeof rootRoute
    }
    '/roofing-magazine/': {
      id: '/roofing-magazine/'
      path: '/roofing-magazine'
      fullPath: '/roofing-magazine'
      preLoaderRoute: typeof RoofingMagazineIndexImport
      parentRoute: typeof rootRoute
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/brontosaurus': typeof BrontosaurusIndexRoute
  '/home': typeof HomeIndexRoute
  '/money-modes': typeof MoneyModesIndexRoute
  '/roofing-magazine': typeof RoofingMagazineIndexRoute
  '/store': typeof StoreIndexRoute
}

export interface FileRoutesByTo {
  '/brontosaurus': typeof BrontosaurusIndexRoute
  '/home': typeof HomeIndexRoute
  '/money-modes': typeof MoneyModesIndexRoute
  '/roofing-magazine': typeof RoofingMagazineIndexRoute
  '/store': typeof StoreIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/brontosaurus/': typeof BrontosaurusIndexRoute
  '/home/': typeof HomeIndexRoute
  '/money-modes/': typeof MoneyModesIndexRoute
  '/roofing-magazine/': typeof RoofingMagazineIndexRoute
  '/store/': typeof StoreIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/brontosaurus'
    | '/home'
    | '/money-modes'
    | '/roofing-magazine'
    | '/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brontosaurus'
    | '/home'
    | '/money-modes'
    | '/roofing-magazine'
    | '/store'
  id:
    | '__root__'
    | '/brontosaurus/'
    | '/home/'
    | '/money-modes/'
    | '/roofing-magazine/'
    | '/store/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BrontosaurusIndexRoute: typeof BrontosaurusIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  MoneyModesIndexRoute: typeof MoneyModesIndexRoute
  RoofingMagazineIndexRoute: typeof RoofingMagazineIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  BrontosaurusIndexRoute: BrontosaurusIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  MoneyModesIndexRoute: MoneyModesIndexRoute,
  RoofingMagazineIndexRoute: RoofingMagazineIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/brontosaurus/",
        "/home/",
        "/money-modes/",
        "/roofing-magazine/",
        "/store/"
      ]
    },
    "/brontosaurus/": {
      "filePath": "brontosaurus/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/money-modes/": {
      "filePath": "money-modes/index.tsx"
    },
    "/roofing-magazine/": {
      "filePath": "roofing-magazine/index.tsx"
    },
    "/store/": {
      "filePath": "store/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
